CREATE TABLE IF NOT EXISTS ${DATABASE_NAME}.${EMP_TABLES} (
    employee_id INT,
    employee_name STRING,
    salary_emp STRING,
    department_id INT
)
PARTITIONED BY (dt STRING)
COMMENT "EMPLOYEE TABLE"
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;