CREATE TABLE IF NOT EXISTS ${TBL_EMPLOYEE} (
    employee_id INT,
    employee_name STRING,
    salary_emp DOUBLE,
    department_id INT
)
PARTITIONED BY (dt STRING)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE
TBLPROPERTIES ("transactional" = 'false');