CREATE TABLE IF NOT EXISTS hive_shell_sample.departments (
    department_id INT,
    department_name STRING
)
PARTITIONED BY(dt STRING)
COMMENT "EMPLOYEE TABLE"
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE;